export const mock_accounts = [
  {
    id: 1,
    accountNumber: '1000',
    accountName: 'Cash on Hand',
    parentAccount: null,
    description: 'All cash on hand',
    type: 'Assets/Current Assets/Cash on Hand',
    debit: null,
    credit: null,
  },
  {
    id: 2,
    accountNumber: '1010',
    accountName: 'Bank ADCB',
    parentAccount: 'Cash on Hand',
    description: 'Bank ADCB account',
    type: 'Assets/Current Assets/Bank Accounts/Bank ADCB',
    debit: '5000',
    credit: null,
  },
  {
    id: 3,
    accountNumber: '1011',
    accountName: 'Emirates NBD',
    parentAccount: 'Cash on Hand',
    description: 'Emirates NBD account',
    type: 'Assets/Current Assets/Bank Accounts/Emirates NBD Bank',
    debit: null,
    credit: null,
  },
  {
    id: 4,
    accountNumber: '1012',
    accountName: 'Abu Dhabi Islamic Bank',
    parentAccount: 'Cash on Hand',
    description: 'Abu Dhabi Islamic Bank account',
    type: 'Assets/Current Assets/Bank Accounts/Abu Dhabi Islamic Bank',
    debit: null,
    credit: null,
  },
  {
    id: 5,
    accountNumber: '1020',
    accountName: 'Accounts Receivable',
    parentAccount: 'Current Assets',
    description: 'Accounts receivable from clients',
    type: 'Assets/Current Assets/Accounts Receivable/Client',
    debit: null,
    credit: '7000',
  },
  {
    id: 6,
    accountNumber: '2000',
    accountName: 'Accounts Payable',
    parentAccount: null,
    description: 'All liabilities',
    type: 'Liabilities/Current Liabilities/Accounts Payable/Vendor',
    debit: '1000',
    credit: null,
  },
  {
    id: 7,
    accountNumber: '3000',
    accountName: 'Owner’s Equity',
    parentAccount: null,
    description: 'Owner equity',
    type: 'Equity/Owner’s Capital / Share Capital',
    debit: '3000',
    credit: null,
  },
  {
    id: 8,
    accountNumber: '4000',
    accountName: 'Product Sales',
    parentAccount: null,
    description: 'Revenue from product sales',
    type: 'Revenue/Sales / Service Revenue/Product Sales',
    debit: '6000',
    credit: null,
  },
  {
    id: 9,
    accountNumber: '5000',
    accountName: 'Raw Materials',
    parentAccount: null,
    description: 'Raw materials for projects',
    type: 'Cost of Goods Sold (COGS)/Raw Materials / Purchases (Choose project)',
    debit: '9000',
    credit: null,
  },
  {
    id: 10,
    accountNumber: '6000',
    accountName: 'Salaries & Wages',
    parentAccount: null,
    description: 'Salaries and wages',
    type: 'Operating Expenses/General & Administrative/Salaries & Wages',
    debit: null,
    credit: '2500',
  },
  {
    id: 11,
    accountNumber: '6010',
    accountName: 'John Doe Salary',
    parentAccount: 'Salaries & Wages',
    description: 'Employee John Doe salary',
    type: 'Operating Expenses/General & Administrative/Salaries & Wages/Employee names select',
    debit: null,
    credit: '4000',
  },
];

export const mock_voucher = [
  {
    voucherNumber: 'JV-001',
    accountNumber: '1010',
    accountName: 'Cash on Hand',
    debit: 25000.0,
    credit: 0,
    narration: 'Being cash received from customer',
  },
  {
    voucherNumber: 'JV-001',
    accountNumber: '2010',
    accountName: 'Accounts Payable',
    debit: 0,
    credit: 15000.0,
    narration: 'Being part payment made to supplier',
  },
  {
    voucherNumber: 'JV-001',
    accountNumber: '2020',
    accountName: 'Bank ADCB',
    debit: 0,
    credit: 10000.0,
    narration: 'Being funds transferred to bank account',
  },
  {
    voucherNumber: 'JV-002',
    accountNumber: '1010',
    accountName: 'Cash on Hand',
    debit: 5000.0,
    credit: 0,
    narration: 'Being cash sales made during the day',
  },
  {
    voucherNumber: 'JV-002',
    accountNumber: '4010',
    accountName: 'Sales Revenue',
    debit: 0,
    credit: 5000.0,
    narration: 'Being revenue booked for sales',
  },
];

export const mock_posted_voucher = [
  {
    voucherNumber: 'JV-003',
    accountNumber: '1010',
    accountName: 'Cash on Hand',
    debit: 12000.0,
    credit: 0,
    narration: 'Being cash received from client A',
  },
  {
    voucherNumber: 'JV-003',
    accountNumber: '3010',
    accountName: 'Accounts Receivable',
    debit: 0,
    credit: 7000.0,
    narration: 'Being partial payment recorded for invoice #123',
  },
  {
    voucherNumber: 'JV-003',
    accountNumber: '3020',
    accountName: 'Bank Emirates',
    debit: 0,
    credit: 5000.0,
    narration: 'Being funds deposited in bank account',
  },
  {
    voucherNumber: 'JV-004',
    accountNumber: '1010',
    accountName: 'Cash on Hand',
    debit: 8000.0,
    credit: 0,
    narration: 'Being cash sales collected today',
  },
  {
    voucherNumber: 'JV-004',
    accountNumber: '4020',
    accountName: 'Service Revenue',
    debit: 0,
    credit: 8000.0,
    narration: 'Being revenue booked for service rendered',
  },
  {
    voucherNumber: 'JV-005',
    accountNumber: '1030',
    accountName: 'Petty Cash',
    debit: 2000.0,
    credit: 0,
    narration: 'Being petty cash replenished',
  },
  {
    voucherNumber: 'JV-005',
    accountNumber: '5010',
    accountName: 'Office Supplies Expense',
    debit: 0,
    credit: 2000.0,
    narration: 'Being purchase of stationery',
  },
];

export const products_services = [
  { name: 'Raw Materials' },
  { name: 'Office Supplies' },
  { name: 'Packaging Materials' },
  { name: 'IT Equipment' },
  { name: 'Construction Materials' },
  { name: 'Consulting Services' },
  { name: 'Maintenance Services' },
  { name: 'Logistics & Freight' },
  { name: 'Warehousing Services' },
  { name: 'Professional Training' },
  { name: 'Software Licenses' },
  { name: 'Security Services' },
];

export const quantity_measurements = [
  { name: 'Kilogram (kg)' },
  { name: 'Gram (g)' },
  { name: 'Milligram (mg)' },
  { name: 'Pound (lb)' },
  { name: 'Ounce (oz)' },
  { name: 'Tonne (t)' },

  { name: 'Piece (pc)' },
  { name: 'Dozen (dz)' },
  { name: 'Pack' },
  { name: 'Box' },
  { name: 'Carton' },
  { name: 'Bottle' },
  { name: 'Bag' },
  { name: 'Other' },
];

export const locations = [
  { name: 'Dubai' },
  { name: 'Abu Dhabi' },
  { name: 'Sharjah' },
  { name: 'Ajman' },
  { name: 'Ras Al Khaimah' },
  { name: 'Fujairah' },
  { name: 'Umm Al Quwain' },
  { name: 'Al Ain' },
];

export const mock_vendors = [{ name: 'Dubai Police' }, { name: 'Sharjah Mueseum' }];
export const order_type = [{ name: 'Local Purchase Order' }, { name: 'Purchase Order' }];
export const invoice_type = [
  { name: 'Tax Cash Invoice' },
  { name: 'Tax Credit Invoice' },
  { name: 'Non-Tax Invoice' },
];

export const mock_local_purchase = [
  {
    orderNumber: 'PR-001',
    quantity: '10',
    rate: '100',
    amount: '1000',
    vendor: '001',
    profileImageFileUrl: '',
    address: 'Dubai',
    location: 'Dubai',
    terms: 'Net 30',
    message: '....',
    products: [
      {
        productName: 'Raw Materials',
        unit: 'Kilogram (kg)',
        quantity: 10,
        rate: 100,
        amount: 1000,
      },
      {
        productName: 'Packaging Materials',
        unit: 'Box',
        quantity: 5,
        rate: 50,
        amount: 250,
      },
    ],
  },
  {
    orderNumber: 'PR-002',
    quantity: '20',
    rate: '200',
    amount: '4000',
    vendor: '002',
    profileImageFileUrl: '',
    address: 'Dubai',
    location: 'Sharjah',
    terms: 'FOB Destination',
    message: 'test msg',
    products: [
      {
        productName: 'Office Supplies',
        unit: 'Piece (pc)',
        quantity: 20,
        rate: 200,
        amount: 4000,
      },
      {
        productName: 'Furniture',
        unit: 'Carton',
        quantity: 2,
        rate: 1500,
        amount: 3000,
      },
    ],
  },
];

export const lpo_terms = [
  { name: 'Net 30' },
  { name: 'FOB Destination' },
  { name: 'Delivery within 7 days' },
  { name: 'Warranty 12 months' },
  { name: 'No partial shipments' },
  { name: 'Invoice must reference LPO number' },
];

export const currencies = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: 'AE' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', flag: 'SA' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', flag: 'QA' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: 'KW' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', flag: 'OM' },
  { code: 'USD', name: 'US Dollar', symbol: '$', flag: 'US' },
  { code: 'EUR', name: 'Euro', symbol: '€', flag: 'EU' },
];

export const mock_payment_voucher = [
  {
    orderNumber: 'V-001',
    accNumber: '1000',
    accName: 'Cash on Hand',
    quantity: '10',
    rate: '100',
    amount: '1000',
    vendor: 'Dubai Police',
    profileImageFileUrl: '',
    address: 'Dubai',
    location: 'Lorem Ipsum is simply dummy text.',
    terms: 'Cash',
    message: '....',
    products: [
      {
        productName: 'Raw Materials',
        unit: 'Kilogram (kg)',
        quantity: 10,
        rate: 100,
        amount: 1000,
      },
      {
        productName: 'Packaging Materials',
        unit: 'Box',
        quantity: 5,
        rate: 50,
        amount: 250,
      },
    ],
  },
  {
    orderNumber: 'V-002',
    accNumber: '2000',
    accName: 'Emirates NBD',
    quantity: '20',
    rate: '200',
    amount: '4000',
    vendor: 'Sharjah Mueseum',
    profileImageFileUrl: '',
    address: 'Dubai',
    location: 'It is a long established fact that',
    terms: 'Credit Card',
    message: 'test msg',
    products: [
      {
        productName: 'Office Supplies',
        unit: 'Piece (pc)',
        quantity: 20,
        rate: 200,
        amount: 4000,
      },
      {
        productName: 'Furniture',
        unit: 'Carton',
        quantity: 2,
        rate: 1500,
        amount: 3000,
      },
    ],
  },
];

export const payment_method = [{ name: 'Cash' }, { name: 'Credit Card' }, { name: 'Debit Card' }];
export const payment_receivers = [{ name: 'Clients' }, { name: 'Employees' }, { name: 'Other' }];
export const mock_employees = [
  { name: 'Randa' },
  { name: 'Umair' },
  { name: 'Ala' },
  { name: 'Binshida' },
];

export const purchase_order = [
  {
    id: 'PR-001',
    name: 'Office Supplies',
    supplier: 'Stationery World LLC',
    date: '2025-10-10',
    totalAmount: 1250.75,
    status: 'Approved',
  },
  {
    id: 'PR-002',
    name: 'Laptop Purchase',
    supplier: 'Techno Computers FZE',
    date: '2025-10-12',
    totalAmount: 8200.0,
    status: 'Pending',
  },
  {
    id: 'PR-003',
    name: 'Cleaning Materials',
    supplier: 'CleanPro Supplies',
    date: '2025-10-15',
    totalAmount: 560.4,
    status: 'Delivered',
  },
  {
    id: 'PR-004',
    name: 'Furniture Order',
    supplier: 'Office Deco Trading',
    date: '2025-10-18',
    totalAmount: 4320.9,
    status: 'Approved',
  },
  {
    id: 'PR-005',
    name: 'Printer Ink Cartridges',
    supplier: 'PrintMart Qatar',
    date: '2025-10-20',
    totalAmount: 980.0,
    status: 'Cancelled',
  },
];

export const mock_assets = [
  {
    orderNumber: 'Machinery and Tools',
    quantity: '10',
    rate: '100',
    amount: '1000',
    vendor: '001',
    profileImageFileUrl: '',
    address: 'Dubai',
    location: 'Dubai',
    terms: 'Net 30',
    message: '....',
    products: [
      {
        productName: 'Raw Materials',
        unit: 'Kilogram (kg)',
        quantity: 10,
        rate: 100,
        amount: 1000,
      },
      {
        productName: 'Packaging Materials',
        unit: 'Box',
        quantity: 5,
        rate: 50,
        amount: 250,
      },
    ],
  },
  {
    orderNumber: 'Office Equipment',
    quantity: '20',
    rate: '200',
    amount: '4000',
    vendor: '002',
    profileImageFileUrl: '',
    address: 'Dubai',
    location: 'Sharjah',
    terms: 'FOB Destination',
    message: 'test msg',
    products: [
      {
        productName: 'Office Supplies',
        unit: 'Piece (pc)',
        quantity: 20,
        rate: 200,
        amount: 4000,
      },
      {
        productName: 'Furniture',
        unit: 'Carton',
        quantity: 2,
        rate: 1500,
        amount: 3000,
      },
    ],
  },
];

export const attendance_register = [
  {
    id: '01',
    employeeName: 'John Smith',
    employeeEmail: 'john.smith@company.com',
    department: 'Accounts',
    designation: 'Senior Accountant',
    attendanceCode: 'Present',
  },
  {
    id: '02',
    employeeName: 'Sarah Ali',
    employeeEmail: 'sarah.ali@company.com',
    department: 'Human Resources',
    designation: 'HR Executive',
    attendanceCode: 'Absent',
  },
  {
    id: '03',
    employeeName: 'Ahmed Khan',
    employeeEmail: 'ahmed.khan@company.com',
    department: 'Sales',
    designation: 'Sales Executive',
    attendanceCode: 'Leave',
  },
  {
    id: '04',
    employeeName: 'Priya Sharma',
    employeeEmail: 'priya.sharma@company.com',
    department: 'IT',
    designation: 'Software Engineer',
    attendanceCode: 'Present',
  },
  {
    id: '05',
    employeeName: 'Mohammed Faisal',
    employeeEmail: 'mohammed.faisal@company.com',
    department: 'Operations',
    designation: 'Operations Supervisor',
    attendanceCode: 'Weekly Off',
  },
  {
    id: '06',
    employeeName: 'Emily Davis',
    employeeEmail: 'emily.davis@company.com',
    department: 'Marketing',
    designation: 'Marketing Coordinator',
    attendanceCode: 'Holiday',
  },
  {
    id: '07',
    employeeName: 'Ravi Patel',
    employeeEmail: 'ravi.patel@company.com',
    department: 'Procurement',
    designation: 'Purchase Officer',
    attendanceCode: 'Present',
  },
  {
    id: '08',
    employeeName: 'Fatima Noor',
    employeeEmail: 'fatima.noor@company.com',
    department: 'Customer Support',
    designation: 'Support Representative',
    attendanceCode: 'Present',
  },
  {
    id: '09',
    employeeName: 'Daniel Thomas',
    employeeEmail: 'daniel.thomas@company.com',
    department: 'Finance',
    designation: 'Financial Analyst',
    attendanceCode: 'Absent',
  },
  {
    id: '10',
    employeeName: 'Aisha Mohammed',
    employeeEmail: 'aisha.mohammed@company.com',
    department: 'Administration',
    designation: 'Office Administrator',
    attendanceCode: 'Present',
  },
];

export const expense_register = [
  {
    date: '2025-10-01',
    expenseId: 'EXP001',
    description: 'Printer ink and paper purchase',
    paidTo: 'Stationery World LLC',
    paymentMode: 'Cash',
    amount: 150.0,
    tax: 7.5,
    total: 157.5,
  },
  {
    date: '2025-10-02',
    expenseId: 'EXP002',
    description: 'Client meeting travel expenses',
    paidTo: 'Metro Taxi Services',
    paymentMode: 'Card',
    amount: 80.0,
    tax: 0,
    total: 80.0,
  },
  {
    date: '2025-10-03',
    expenseId: 'EXP003',
    description: 'Electricity bill for October',
    paidTo: 'DEWA',
    paymentMode: 'Bank Transfer',
    amount: 450.0,
    tax: 0,
    total: 450.0,
  },
  {
    date: '2025-10-04',
    expenseId: 'EXP004',
    description: 'Team lunch for project celebration',
    paidTo: 'City Restaurant',
    paymentMode: 'Cash',
    amount: 210.0,
    tax: 10.5,
    total: 220.5,
  },
  {
    date: '2025-10-05',
    expenseId: 'EXP005',
    description: 'Air conditioner maintenance',
    paidTo: 'CoolTech Services',
    paymentMode: 'Bank Transfer',
    amount: 320.0,
    tax: 16.0,
    total: 336.0,
  },
  {
    date: '2025-10-06',
    expenseId: 'EXP006',
    description: 'Office internet subscription renewal',
    paidTo: 'Du Telecom',
    paymentMode: 'Online Payment',
    amount: 299.0,
    tax: 14.95,
    total: 313.95,
  },
  {
    date: '2025-10-07',
    expenseId: 'EXP007',
    description: 'Office cleaning services',
    paidTo: 'CleanPro Facility Services',
    paymentMode: 'Cash',
    amount: 180.0,
    tax: 9.0,
    total: 189.0,
  },
  {
    date: '2025-10-08',
    expenseId: 'EXP008',
    description: 'Fuel for company vehicle',
    paidTo: 'ENOC Fuel Station',
    paymentMode: 'Card',
    amount: 120.0,
    tax: 0,
    total: 120.0,
  },
  {
    date: '2025-10-09',
    expenseId: 'EXP009',
    description: 'Office snacks and beverages',
    paidTo: 'Carrefour',
    paymentMode: 'Cash',
    amount: 95.0,
    tax: 4.75,
    total: 99.75,
  },
  {
    date: '2025-10-10',
    expenseId: 'EXP010',
    description: 'Monthly software subscription',
    paidTo: 'Microsoft 365',
    paymentMode: 'Online Payment',
    amount: 430.0,
    tax: 21.5,
    total: 451.5,
  },
];
