export const employees = [
  {
    empId: '101',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'CEO',
    department: 'Management',
    email: 'nannie.abernathy70@yahoo.com',
    address: '908 Jack Locks',
    name: 'Jayvion Simon',
    userName: 'Jayvion101',
    isVerified: true,
    company: 'Lueilwitz and Sons',
    country: 'United States',
    avatarUrl: '/assets/images/mock/avatar/avatar-1.webp',
    phoneNumber: '+1 202-555-0143',
    type: 'external',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: true,
    taskPermissionLevel: 2,
    level: 2,
  },
  {
    empId: '102',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'CTO',
    department: 'Management',
    email: 'ashlynn.ohara62@gmail.com',
    address: '908 Jack Locks',
    name: 'Lucian Obrien',
    userName: 'Lucian102',
    isVerified: true,
    company: 'Gleichner, Mueller and Tromp',
    country: 'Canada',
    avatarUrl: '/assets/images/mock/avatar/avatar-2.webp',
    phoneNumber: '+1 416-555-0198',
    type: 'internal',
    empStatus: 'Vacation',
    status: 'Disabled',
    password: '',
    isTaskExempted: true,
    taskPermissionLevel: 3,
    level: 3,
  },
  {
    empId: '103',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Project Coordinator',
    department: 'IT',
    email: 'milo.farrell@hotmail.com',
    address: '908 Jack Locks',
    name: 'Deja Brady',
    userName: 'Deja103',
    isVerified: true,
    company: 'Nikolaus - Leuschke',
    country: 'United Kingdom',
    avatarUrl: '/assets/images/mock/avatar/avatar-3.webp',
    phoneNumber: '+44 20 7946 0958',
    type: 'myteam',
    empStatus: 'Sick Leave',
    status: 'Active',
    password: '',
    isTaskExempted: true,
    taskPermissionLevel: 1,
    level: 1,
  },
  {
    empId: '104',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Team Leader',
    department: 'IT',
    email: 'violet.ratke86@yahoo.com',
    address: '908 Jack Locks',
    name: 'Harrison Stein',
    userName: 'Harrison104',
    isVerified: false,
    company: 'Hegmann, Kreiger and Bayer',
    country: 'Australia',
    avatarUrl: '/assets/images/mock/avatar/avatar-4.webp',
    phoneNumber: '+61 2 9876 5432',
    type: 'internal',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 1,
    level: 1,
  },
  {
    empId: '105',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Software Developer',
    department: 'IT',
    email: 'letha.lubowitz24@yahoo.com',
    address: '908 Jack Locks',
    name: 'Reece Chung',
    userName: 'Reece105',
    isVerified: false,
    company: 'Grimes Inc',
    country: 'India',
    avatarUrl: '/assets/images/mock/avatar/avatar-5.webp',
    phoneNumber: '+91 22 1234 5678',
    type: 'myteam',
    empStatus: 'Vacation',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 2,
    level: 2,
  },
  {
    empId: '106',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Marketing Strategist',
    department: 'Marketing',
    email: 'aditya.greenfelder31@gmail.com',
    address: '908 Jack Locks',
    name: 'Lainey Davidson',
    userName: 'Lainey106',
    isVerified: true,
    company: 'Durgan - Murazik',
    country: 'Germany',
    avatarUrl: '/assets/images/mock/avatar/avatar-6.webp',
    phoneNumber: '+49 30 123456',
    type: 'internal',
    empStatus: 'Sick Leave',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 2,
    level: 2,
  },
  {
    empId: '107',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Data Analyst',
    department: 'IT',
    email: 'lenna.bergnaum27@hotmail.com',
    address: '908 Jack Locks',
    name: 'Cristopher Cardenas',
    userName: 'Cristopher107',
    isVerified: false,
    company: 'Altenwerth, Medhurst and Roberts',
    country: 'France',
    avatarUrl: '/assets/images/mock/avatar/avatar-7.webp',
    phoneNumber: '+33 1 23456789',
    type: 'external',
    empStatus: 'Vacation',
    status: 'Disabled',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 3,
    level: 3,
  },
  {
    empId: '108',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Product Owner',
    department: 'Management',
    email: 'luella.ryan33@gmail.com',
    address: '908 Jack Locks',
    name: 'Melanie Noble',
    userName: 'Melanie108',
    isVerified: false,
    company: 'Raynor Group',
    country: 'Japan',
    avatarUrl: '/assets/images/mock/avatar/avatar-8.webp',
    phoneNumber: '+81 3 1234 5678',
    type: 'internal',
    empStatus: 'On Duty',
    status: 'Disabled',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 3,
    level: 3,
  },
  {
    empId: '109',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b9',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Graphic Designer',
    department: 'IT',
    email: 'joana.simonis84@gmail.com',
    address: '908 Jack Locks',
    name: 'Chase Day',
    userName: 'Chase109',
    isVerified: false,
    company: 'Mraz, Donnelly and Collins',
    country: 'China',
    avatarUrl: '/assets/images/mock/avatar/avatar-9.webp',
    phoneNumber: '+86 10 1234 5678',
    type: 'myteam',
    empStatus: 'Vacation',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 3,
    level: 3,
  },
  {
    empId: '110',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b10',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Operations Manager',
    department: 'IT',
    email: 'marjolaine.white94@gmail.com',
    address: '908 Jack Locks',
    name: 'Shawn Manning',
    userName: 'Shawn110',
    isVerified: false,
    company: 'Padberg - Bailey',
    country: 'Brazil',
    avatarUrl: '/assets/images/mock/avatar/avatar-10.webp',
    phoneNumber: '+55 11 2345-6789',
    type: 'internal',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 1,
    level: 1,
  },
  {
    empId: '111',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b11',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Customer Support Specialist',
    department: 'Management',
    email: 'vergie.block82@hotmail.com',
    address: '908 Jack Locks',
    name: 'Soren Durham',
    userName: 'Soren111',
    isVerified: true,
    company: 'Heidenreich, Stokes and Parker',
    country: 'South Africa',
    avatarUrl: '/assets/images/mock/avatar/avatar-11.webp',
    phoneNumber: '+27 11 123 4567',
    type: 'myteam',
    empStatus: 'On Duty',
    status: 'Disabled',
    password: '',
    isTaskExempted: true,
    taskPermissionLevel: 2,
    level: 2,
  },
  {
    empId: '112',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b12',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Sales Manager',
    department: 'Management',
    email: 'vito.hudson@hotmail.com',
    address: '908 Jack Locks',
    name: 'Cortez Herring',
    userName: 'Cortez112',
    isVerified: true,
    company: 'Pagac and Sons',
    country: 'Russia',
    avatarUrl: '/assets/images/mock/avatar/avatar-12.webp',
    phoneNumber: '+7 495 123-4567',
    type: 'internal',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 1,
    level: 1,
  },
  {
    empId: '113',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b13',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'HR Recruiter',
    department: 'Human Resources',
    email: 'tyrel.greenholt@gmail.com',
    address: '908 Jack Locks',
    name: 'Brycen Jimenez',
    userName: 'Brycen113',
    isVerified: true,
    company: 'Rempel, Hand and Herzog',
    country: 'Mexico',
    avatarUrl: '/assets/images/mock/avatar/avatar-13.webp',
    phoneNumber: '+52 55 1234 5678',
    type: 'external',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 3,
    level: 3,
  },
  {
    empId: '114',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b14',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Business Consultant',
    department: 'IT',
    email: 'dwight.block85@yahoo.com',
    address: '908 Jack Locks',
    name: 'Giana Brandt',
    userName: 'Giana114',
    isVerified: false,
    company: 'Dare - Treutel',
    country: 'Italy',
    avatarUrl: '/assets/images/mock/avatar/avatar-14.webp',
    phoneNumber: '+39 06 123 4567',
    type: 'internal',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 2,
    level: 2,
  },
  {
    empId: '115',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b15',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Financial Planner',
    department: 'Finance',
    email: 'mireya13@hotmail.com',
    address: '908 Jack Locks',
    name: 'Aspen Schmitt',
    userName: 'Aspen115',
    isVerified: false,
    company: 'Kihn, Marquardt and Crist',
    country: 'Spain',
    avatarUrl: '/assets/images/mock/avatar/avatar-15.webp',
    phoneNumber: '+34 91 123 4567',
    type: 'myteam',
    empStatus: 'Sick Leave',
    status: 'Disabled',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 1,
    level: 1,
  },
  {
    empId: '116',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b16',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Network Engineer',
    department: 'IT',
    email: 'dasia.jenkins@hotmail.com',
    address: '908 Jack Locks',
    name: 'Colten Aguilar',
    userName: 'Colten116',
    isVerified: false,
    company: 'Nolan - Kunde',
    country: 'Netherlands',
    avatarUrl: '/assets/images/mock/avatar/avatar-16.webp',
    phoneNumber: '+31 20 123 4567',
    type: 'internal',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 3,
    level: 3,
  },
  {
    empId: '117',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b17',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Content Creator',
    department: 'IT',
    email: 'benny89@yahoo.com',
    address: '908 Jack Locks',
    name: 'Angelique Morse',
    userName: 'Angelique117',
    isVerified: true,
    company: 'Wuckert Inc',
    country: 'Sweden',
    avatarUrl: '/assets/images/mock/avatar/avatar-17.webp',
    phoneNumber: '+46 8 123 456',
    type: 'myteam',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 3,
    level: 3,
  },
  {
    empId: '118',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b18',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Quality Assurance Tester',
    department: 'Quality Assurance',
    email: 'dawn.goyette@gmail.com',
    address: '908 Jack Locks',
    name: 'Selina Boyer',
    userName: 'Selina118',
    isVerified: false,
    company: 'Dibbert Inc',
    country: 'Switzerland',
    avatarUrl: '/assets/images/mock/avatar/avatar-18.webp',
    phoneNumber: '+41 22 123 45 67',
    type: 'internal',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 2,
    level: 2,
  },
  {
    empId: '119',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b19',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Public Relations Officer',
    department: 'Management',
    email: 'zella.hickle4@yahoo.com',
    address: '908 Jack Locks',
    name: 'Lawson Bass',
    userName: 'Lawson119',
    isVerified: false,
    company: 'Goyette and Sons',
    country: 'South Korea',
    avatarUrl: '/assets/images/mock/avatar/avatar-19.webp',
    phoneNumber: '+82 2 123 4567',
    type: 'external',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    isTaskExempted: false,
    taskPermissionLevel: 2,
    level: 2,
  },
  {
    empId: '120',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b20',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'IT Administrator',
    department: 'IT',
    email: 'avery43@hotmail.com',
    address: '908 Jack Locks',
    name: 'Ariana Lang',
    userName: 'Ariana120',
    isVerified: false,
    company: 'Feest Group',
    country: 'Argentina',
    avatarUrl: '/assets/images/mock/avatar/avatar-20.webp',
    phoneNumber: '+54 11 1234-5678',
    type: 'internal',
    empStatus: 'Vacation',
    status: 'Disabled',
    password: '',
    isTaskExempted: true,
    taskPermissionLevel: 3,
    level: 3,
  },
];

export const departments = [
  `IT`,
  `Management`,
  `Marketing`,
  `Quality Assurance`,
  `Finance`,
  `Human Resources`,
];

export const status = [`Active`, `Disabled`];

export const designations = [
  `CEO`,
  `CTO`,
  `Project Coordinator`,
  `Team Leader`,
  `Software Developer`,
  `Marketing Strategist`,
  `Data Analyst`,
  `Product Owner`,
  `Graphic Designer`,
  `Operations Manager`,
  `Customer Support Specialist`,
  `Sales Manager`,
  `HR Recruiter`,
  `Business Consultant`,
];

export const MOCK_DESIGNATIONS = [
  { id: 1, name: 'Admin', nameAr: 'مدير', noOfEmployees: 5, isActive: true },
  { id: 2, name: 'HR', nameAr: 'موارد بشرية', noOfEmployees: 8, isActive: true },
  { id: 3, name: 'Developer', nameAr: 'مطور', noOfEmployees: 20, isActive: true },
  { id: 4, name: 'Designer', nameAr: 'مصمم', noOfEmployees: 12, isActive: true },
  { id: 5, name: 'Manager', nameAr: 'مدير', noOfEmployees: 7, isActive: true },
  { id: 6, name: 'QA Engineer', nameAr: 'مهندس ضمان الجودة', noOfEmployees: 10, isActive: true },
];

export const MOCK_STATUS = [
  { id: 1, name: 'On Duty', nameAr: 'في الخدمة', isActive: true, colorCode: '#28a745' },
  { id: 2, name: 'Vacation', nameAr: 'إجازة', isActive: true, colorCode: '#ffc107' },
  { id: 3, name: 'Sick Leave', nameAr: 'إجازة مرضية', isActive: true, colorCode: '#dc3545' },
  { id: 4, name: 'Mission', nameAr: 'مهمة', isActive: true, colorCode: '#17a2b8' },
  { id: 5, name: 'Business Trip', nameAr: 'رحلة عمل', isActive: true, colorCode: '#007bff' },
  { id: 6, name: 'Training', nameAr: 'تدريب', isActive: true, colorCode: '#6c757d' },
];

export const PRESET_COLORS = [
  '#00AB55', // Green
  '#000000', // Black
  '#FFFFFF', // White
  '#FFC0CB', // Pink
  '#FF4842', // Red
  '#1890FF', // Blue
  '#94D82D', // Lime Green
  '#FFC107', // Yellow
  '#04297A', // Dark Blue
  '#7A0C2E', // Maroon
  '#54D62C', // Bright Green
  '#FF7A45', // Orange
  '#7635dc', // Purple
  '#22c55e', // Emerald Green
  '#842d73', // Dark Magenta
  '#065e60', // Dark Cyan
  '#facc15', // Bright Yellow
  '#6366f1', // Indigo
  '#ec4899', // Fuchsia
  '#f97316', // Bright Orange
  '#0891b2', // Cyan
  '#65a30d', // Olive Green
  '#be185d', // Dark Pink
  '#4b5563', // Gray
  '#14b8a6', // Teal
  '#d946ef', // Violet
  '#eab308', // Amber
  '#0ea5e9', // Sky Blue
  '#ef4444', // Bright Red
  '#8b5cf6', // Amethyst
  '#F2CB60', // Approx of yellow gradient
  '#2FBBA8',
];

export const _levels = Array.from({ length: 3 }, (_, index) => ({
  id: index + 1,
  value: index + 1,
}));

export const userRights = [
  {
    id: 37,
    moduleId: 1,
    moduleAccessId: 1,
    name: 'Create',
    isSelected: true,
    moduleName: 'Project',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'Create Projects',
    refinedArabicName: 'إنشاء المشاريع',
  },
  {
    id: 38,
    moduleId: 1,
    moduleAccessId: 2,
    name: 'ViewAll',
    isSelected: true,
    moduleName: 'Project',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'View All projects details',
    refinedArabicName: 'عرض تفاصيل جميع المشاريع (حتى إذا لم يكن عضوًا)',
  },
  {
    id: 39,
    moduleId: 2,
    moduleAccessId: 3,
    name: 'Create',
    isSelected: false,
    moduleName: 'Meeting',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'Create Meetings',
    refinedArabicName: 'إنشاء الاجتماعات',
  },
  {
    id: 40,
    moduleId: 3,
    moduleAccessId: 4,
    name: 'ViewAll',
    isSelected: true,
    moduleName: 'Client',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'View All clients ',
    refinedArabicName: 'عرض جميع العملاء (حتى إذا لم يكن عضوًا)',
  },
  {
    id: 41,
    moduleId: 4,
    moduleAccessId: 5,
    name: 'Create',
    isSelected: true,
    moduleName: 'Employee',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'Mark as admin',
    refinedArabicName:
      'التعيين كمدير (يمكن للمدير عرض لوحة تحكم المدير، إضافة/حذف الموظفين، تعديل الهيكل التنظيمي، عرض تفاصيل الموظفين، إلخ.)',
  },
];

export const department_levels = [
  {
    id: 1,
    name: 'Department',
    nameAr: 'قسم',
    noOfEmployees: 5,
    isActive: true,
    departments: [
      { id: 1, name: 'IT', nameAr: 'تكنولوجيا المعلومات', noOfEmployees: 5 },
      { id: 2, name: 'HR', nameAr: 'الموارد البشرية', noOfEmployees: 5 },
      { id: 3, name: 'Development', nameAr: 'التطوير', noOfEmployees: 5 },
      { id: 4, name: 'Design', nameAr: 'التصميم', noOfEmployees: 5 },
    ],
  },
  {
    id: 2,
    name: 'Division',
    nameAr: 'إدارة',
    noOfEmployees: 8,
    isActive: true,
    divisions: [
      {
        id: 1,
        name: 'Software Development',
        nameAr: 'تطوير البرمجيات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 2,
        name: 'Network Administration ',
        nameAr: 'إدارة الشبكات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 3,
        name: 'Recruitment and Talent Acquisition',
        nameAr: 'التوظيف واكتساب المواهب',
        noOfEmployees: 5,
        deptName: 'HR',
        deptNameAr: 'الموارد البشرية',
      },
      {
        id: 4,
        name: 'Graphic Design',
        nameAr: 'تصميم الجرافيك',
        noOfEmployees: 5,
        deptName: 'Design',
        deptNameAr: 'التصميم',
      },
    ],
  },
  {
    id: 3,
    name: 'Section',
    nameAr: 'قسم فرعي',
    noOfEmployees: 20,
    isActive: true,
    sections: [
      {
        id: 1,
        name: 'Frontend Development',
        nameAr: 'تطوير الويب',
        noOfEmployees: 5,
        divName: 'Software Development',
        divNameAr: 'تطوير البرمجيات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 2,
        name: 'Network Security',
        nameAr: 'أمان الشبكات',
        noOfEmployees: 5,
        divName: 'Network Administration ',
        divNameAr: 'إدارة الشبكات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 3,
        name: 'Talent Sourcing',
        nameAr: 'البحث عن الموظفين',
        noOfEmployees: 5,
        divName: 'Recruitment and Talent Acquisition',
        divNameAr: 'التوظيف واكتساب المواهب',
        noOfEmployees: 5,
        deptName: 'HR',
        deptNameAr: 'الموارد البشرية',
      },
      {
        id: 4,
        name: 'Branding and Identity Design',
        nameAr: 'تصميم العلامة التجارية والهوية',
        divName: 'Graphic Design',
        divNameAr: 'تصميم الجرافيك',
        noOfEmployees: 5,
        deptName: 'Design',
        deptNameAr: 'التصميم',
      },
    ],
  },
  {
    id: 4,
    name: 'Session',
    nameAr: 'وحدة',
    noOfEmployees: 12,
    isActive: true,
    sessions: [
      {
        id: 1,
        name: 'Angular',
        nameAe: 'Angular',
        secName: 'Frontend Development',
        secNameAr: 'تطوير الويب',
        noOfEmployees: 5,
        divName: 'Software Development',
        divNameAr: 'تطوير البرمجيات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 2,
        name: 'Firewalls',
        nameAe: 'Firewalls',
        secName: 'Network Security',
        secNameAr: 'أمان الشبكات',
        noOfEmployees: 5,
        divName: 'Network Administration ',
        divNameAr: 'إدارة الشبكات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 3,
        name: 'Evaluating Candidate',
        nameAr: 'Evaluating Candidate',
        secName: 'Talent Sourcing',
        secNameAr: 'البحث عن الموظفين',
        noOfEmployees: 5,
        divName: 'Recruitment and Talent Acquisition',
        divNameAr: 'التوظيف واكتساب المواهب',
        noOfEmployees: 5,
        deptName: 'HR',
        deptNameAr: 'الموارد البشرية',
      },
      {
        id: 4,
        name: 'Logo Design',
        nameAr: 'Logo Design',
        secName: 'Branding and Identity Design',
        secNameAr: 'تصميم العلامة التجارية والهوية',
        divName: 'Graphic Design',
        divNameAr: 'تصميم الجرافيك',
        noOfEmployees: 5,
        deptName: 'Design',
        deptNameAr: 'التصميم',
      },
    ],
  },
];

export const task_stats = [
  {
    id: 1,
    count: 12,
    name: 'Completed on time',
    color: '#2B9F57',
  },
  {
    id: 2,
    count: 5,
    name: 'Completed late',
    color: '#B5DE6E',
  },
  {
    id: 3,
    count: 1,
    name: 'Overdue',
    color: '#DF2E2E',
  },
  {
    id: 4,
    count: 7,
    name: 'Working on',
    color: '#FFB85A',
  },
  {
    id: 5,
    count: 3,
    name: 'Not started',
    color: '#236EC0',
  },
  {
    id: 6,
    count: 2,
    name: 'On hold',
    color: '#8EBFCE',
  },
  {
    id: 7,
    count: 4,
    name: 'Waiting for approval',
    color: '#23C0AB',
  },
];

export const project_stat = [
  {
    id: 101,
    count: 12,
    name: 'Hawala',
  },
  {
    id: 102,
    count: 5,
    name: 'Islam Web',
  },
  {
    id: 103,
    count: 1,
    name: 'Zeta',
  },
  {
    id: 104,
    count: 7,
    name: 'Tairra',
  },
  {
    id: 105,
    count: 7,
    name: 'Mahami',
  },
];

export const client_stat = [
  {
    id: 1,
    count: 5,
    name: 'Total Clients',
  },
  {
    id: 2,
    count: 2,
    name: 'Total Leads',
  },
  {
    id: 3,
    count: 3,
    name: 'Active Clients',
  },
  {
    id: 4,
    amount: 5000,
    name: 'Sales Target',
  },
  {
    id: 5,
    amount: 3000,
    name: 'Leads Amount',
  },
  {
    id: 6,
    amount: 2000,
    name: 'Awarded Amount',
  },
  {
    id: 7,
    amount: 1000,
    name: 'Rejected Amount',
  },
];

export const user_gender = [
  {
    value: 1,
    label: 'Male',
  },
  {
    value: 2,
    label: 'Female',
  },
];
