import { CONFIG } from 'src/config-global';

export const projects = [
  {
    id: '101',
    projectId: 'P001',
    projectName: 'NovaSync',
    projectColor: '#FF6B6B',
    projectDescription: 'A cloud-based collaboration platform for remote teams.',
    startDate: '2024-05-01',
    endDate: '2024-09-30',
    departmentName: 'Product Development',
    clientName: 'Skyline Corp',
    goal: 'Streamline communication and file sharing across departments.',
    taskType: ['Design', 'Development', 'Testing', 'Deployment'],
    modules: ['Auth Module', 'Chat Module', 'File Sharing Module', 'Notification System'],
    status: 'Created',
    projectInitiative: 'Dubai AI Centre',
    members: [
      {
        id: 1,
        firstName: 'John Doe',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-1.webp`,
        email: 'johnDoe@gmail.com',
        isOwner: false,
      },
      {
        id: 2,
        firstName: 'Jane Smith',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-2.webp`,
        email: 'janeSmith@gmail.com',
        isOwner: true,
        designationName: 'QA Engineer',
        departmentName: 'IT',
        empStatus: {
          name: 'On Duty',
          colorCode: '#00B894',
        },
      },
    ],
    isActive: true,
    isLive: true,
  },
  {
    id: '102',
    projectId: 'P002',
    projectName: 'BrightMatter',
    projectColor: '#4ECDC4',
    projectDescription: 'AI-powered analytics dashboard for marketing teams.',
    startDate: '2024-06-15',
    endDate: '2024-11-15',
    departmentName: 'Analytics & AI',
    clientName: 'Lumina Digital',
    goal: 'Provide real-time marketing insights with predictive analytics.',
    taskType: ['Research', 'Model Training', 'UI/UX', 'Integration'],
    modules: ['Data Importer', 'Model Engine', 'Dashboard UI', 'Alerts System'],
    status: 'Cancelled',
    projectInitiative: 'Dubai Smart Government',
    members: [
      {
        id: 3,
        firstName: 'Alice Johnson',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-3.webp`,
        email: 'alicJohnson@gmail.com',
        isOwner: false,
      },
    ],
    isActive: false,
    isLive: true,
  },
  {
    id: '103',
    projectId: 'P003',
    projectName: 'TaskForge',
    projectColor: '#FFD93D',
    projectDescription: 'A task management system tailored for enterprise workflow.',
    startDate: '2024-07-10',
    endDate: '2024-12-20',
    departmentName: 'Enterprise Solutions',
    clientName: 'Vertex Technologies',
    goal: 'Simplify task tracking, reporting, and collaboration.',
    taskType: ['Planning', 'Development', 'QA', 'Support'],
    modules: ['Kanban Board', 'Time Tracker', 'Reports Engine', 'Permissions Module'],
    status: 'Created',
    projectInitiative: 'Dubai Police',
    members: [
      {
        id: 4,
        firstName: 'Charlie Green',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-5.webp`,
        email: 'charlieGreen@gmail.com',
        isOwner: true,
      },
      {
        id: 5,
        firstName: 'David Black',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-6.webp`,
        email: 'davidBlack@gmail.com',
        isOwner: true,
      },
      {
        id: 6,
        firstName: 'Eve Adams',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
        email: 'eveAdams@gmail.com',
        isOwner: false,
      },
      {
        id: 7,
        firstName: 'Bob White',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-4.webp`,
        email: 'bobWhite@gmail.com',
        isOwner: false,
      },
    ],
    isActive: true,
    isLive: true,
  },
  {
    id: '104',
    projectId: 'P004',
    projectName: 'PixelPath',
    projectColor: '#A29BFE',
    projectDescription: 'Design collaboration tool for creative teams.',
    startDate: '2024-04-01',
    endDate: '2024-08-01',
    departmentName: 'Creative',
    clientName: 'Pixel Studios',
    goal: 'Enable seamless feedback loops for designers.',
    taskType: ['Design', 'Review', 'Approval'],
    modules: ['Canvas', 'Comment Thread', 'Live Preview'],
    status: 'Cancelled',
    projectInitiative: 'Dubai Design District',
    members: [
      {
        id: 8,
        firstName: 'Fiona Hall',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-8.webp`,
        email: 'fionaHall@gmail.com',
        isOwner: true,
      },
    ],
    isActive: true,
    isLive: true,
  },
  {
    id: '105',
    projectId: 'P005',
    projectName: 'CorePulse',
    projectColor: '#00B894',
    projectDescription: 'A performance analytics tool for HR departments.',
    startDate: '2024-03-10',
    endDate: '2024-07-30',
    departmentName: 'HR Tech',
    clientName: 'TalentIQ',
    goal: 'Track and visualize employee performance in real time.',
    taskType: ['Development', 'Analytics', 'Reporting'],
    modules: ['Employee Metrics', 'Goal Tracking', 'Performance Review'],
    status: 'Created',
    projectInitiative: 'Dubai HR Authority',
    members: [
      {
        id: 9,
        firstName: 'Greg Woods',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-9.webp`,
        email: 'gregWoods@gmail.com',
        isOwner: true,
      },
    ],
    isActive: true,
    isLive: true,
  },

  {
    id: '106',
    projectId: 'P006',
    projectName: 'EchoLane',
    projectColor: '#6C5CE7',
    projectDescription: 'A voice assistant integration for smart home platforms.',
    startDate: '2024-02-01',
    endDate: '2024-10-01',
    departmentName: 'IoT',
    clientName: 'HomeWave Inc.',
    goal: 'Enhance smart home voice experience across devices.',
    taskType: ['Integration', 'Voice Command Mapping', 'Testing'],
    modules: ['Device Bridge', 'Command Center', 'User Profiles'],
    status: 'Created',
    projectInitiative: 'Dubai Future Foundation',
    members: [
      {
        id: 10,
        firstName: 'Helen Troy',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-10.webp`,
        email: 'helenTroy@gmail.com',
        isOwner: false,
      },
    ],
    isActive: false,
    isLive: true,
  },
  {
    id: '107',
    projectId: 'P007',
    projectName: 'ClarityHub',
    projectColor: '#F39C12',
    projectDescription: 'Internal communication and feedback tool.',
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    departmentName: 'Internal Tools',
    clientName: 'Inhouse Team',
    goal: 'Improve transparency and feedback within the organization.',
    taskType: ['Planning', 'Wireframing', 'Dev', 'Launch'],
    modules: ['Feedback Wall', 'Pulse Surveys', 'Admin Panel'],
    status: 'Created',
    projectInitiative: 'Smart Dubai',
    members: [],
    isActive: true,
    isLive: false,
  },
  {
    id: '108',
    projectId: 'P008',
    projectName: 'OrbitOps',
    projectColor: '#0984E3',
    projectDescription: 'Operations management dashboard.',
    startDate: '2024-08-01',
    endDate: '2025-01-10',
    departmentName: 'Operations',
    clientName: 'Orbit Logistics',
    goal: 'Centralize and automate operation workflows.',
    taskType: ['Automation', 'Dashboard', 'Reporting'],
    modules: ['Operations Dashboard', 'Scheduler', 'Alert System'],
    status: 'Created',
    projectInitiative: 'Dubai Digital Authority',
    members: [],
    isActive: true,
    isLive: false,
  },
  {
    id: '109',
    projectId: 'P009',
    projectName: 'SummitView',
    projectColor: '#D63031',
    projectDescription: 'Client-facing performance portal.',
    startDate: '2024-09-15',
    endDate: '2025-02-28',
    departmentName: 'Customer Success',
    clientName: 'Summit Ventures',
    goal: 'Give clients full visibility into their KPIs.',
    taskType: ['Design', 'Backend', 'Client Review'],
    modules: ['Reports', 'Client Access', 'Real-Time KPIs'],
    status: 'Created',
    projectInitiative: 'Dubai Innovation Hub',
    members: [],
    isActive: true,
    isLive: true,
  },
  {
    id: '110',
    projectId: 'P010',
    projectName: 'ZenithDesk',
    projectColor: '#2D3436',
    projectDescription: 'Helpdesk and ticketing system.',
    startDate: '2024-10-01',
    endDate: '2025-03-31',
    departmentName: 'Support Engineering',
    clientName: 'Zenith Group',
    goal: 'Streamline support workflows and ticket resolution.',
    taskType: ['Support Flow', 'UI Dev', 'Integrations'],
    modules: ['Ticketing System', 'Live Chat', 'Email Sync'],
    status: 'Created',
    projectInitiative: 'Dubai Tech Solutions',
    members: [],
    isActive: true,
    isLive: false,
  },
];

export const departments = [
  `IT`,
  `Management`,
  `Marketing`,
  `Quality Assurance`,
  `Finance`,
  `Human Resources`,
];

export const status = [
  `Created`,
  `Started`,
  `Closed`,
  `Cancelled`,
  `In progress`,
  `Postponed`,
  `Amended`,
  `Reopened`,
  `Stopped`,
];

export const statusAr = [
  `تم الإنشاء`,
  `تم البدء`,
  `مغلق`,
  `ملغى`,
  `قيد التنفيذ`,
  `مؤجَّل`,
  `معدَّل`,
  `أُعيد فتحه`,
  `متوقّف`,
];

export const mock_status = [
  { id: 0, name: 'Created', nameAr: 'تم الإنشاء', color: '#4CAF50' },
  { id: 1, name: 'Started', nameAr: 'تم البدء', color: '#2196F3' },
  { id: 2, name: 'Closed', nameAr: 'مغلق', color: '#607D8B' },
  { id: 3, name: 'Cancelled', nameAr: 'ملغى', color: '#F44336' },
  { id: 4, name: 'InProgress', nameAr: 'قيد التنفيذ', color: '#FF9800' },
  { id: 5, name: 'Postpone', nameAr: 'مؤجَّل', color: '#9C27B0' },
  { id: 6, name: 'Amended', nameAr: 'معدَّل', color: '#3F51B5' },
  { id: 7, name: 'Reopened', nameAr: 'أُعيد فتحه', color: '#00BCD4' },
  { id: 8, name: 'Stopped', nameAr: 'متوقّف', color: '#E91E63' },
];

export const designations = [
  `CEO`,
  `CTO`,
  `Project Coordinator`,
  `Team Leader`,
  `Software Developer`,
  `Marketing Strategist`,
  `Data Analyst`,
  `Product Owner`,
  `Graphic Designer`,
  `Operations Manager`,
  `Customer Support Specialist`,
  `Sales Manager`,
  `HR Recruiter`,
  `Business Consultant`,
];

export const MOCK_DESIGNATIONS = [
  { id: 1, name: 'Admin', nameAr: 'مدير', noOfEmployees: 5, isActive: true },
  { id: 2, name: 'HR', nameAr: 'موارد بشرية', noOfEmployees: 8, isActive: true },
  { id: 3, name: 'Developer', nameAr: 'مطور', noOfEmployees: 20, isActive: true },
  { id: 4, name: 'Designer', nameAr: 'مصمم', noOfEmployees: 12, isActive: true },
  { id: 5, name: 'Manager', nameAr: 'مدير', noOfEmployees: 7, isActive: true },
  { id: 6, name: 'QA Engineer', nameAr: 'مهندس ضمان الجودة', noOfEmployees: 10, isActive: true },
];

export const PROJECT_GOALS = [
  { id: 1, name: 'Increase User Engagement', nameAr: 'زيادة تفاعل المستخدمين' },
  { id: 2, name: 'Launch New Feature', nameAr: 'إطلاق ميزة جديدة' },
  { id: 3, name: 'Improve Performance', nameAr: 'تحسين الأداء' },
  { id: 4, name: 'Expand Market Reach', nameAr: 'توسيع نطاق السوق' },
  { id: 5, name: 'Enhance Security', nameAr: 'تعزيز الأمان' },
  { id: 6, name: 'Increase Revenue', nameAr: 'زيادة الإيرادات' },
  { id: 7, name: 'User  Feedback Integration', nameAr: 'دمج ملاحظات المستخدمين' },
  { id: 8, name: 'Team Training', nameAr: 'تدريب الفريق' },
  { id: 9, name: 'Sustainability Initiatives', nameAr: 'مبادرات الاستدامة' },
  { id: 10, name: 'Customer Support Improvement', nameAr: 'تحسين دعم العملاء' },
];

export const PROJECT_INITIATIVES = [
  { name: 'Dubai AI Centre', nameAr: 'مركز دبي للذكاء الاصطناعي' },
  { name: 'Smart City Initiative', nameAr: 'مبادرة المدينة الذكية' },
  { name: 'AI for Healthcare', nameAr: 'الذكاء الاصطناعي للرعاية الصحية' },
  { name: 'AI Education Program', nameAr: 'برنامج التعليم بالذكاء الاصطناعي' },
  { name: 'AI Innovation Hub', nameAr: 'مركز الابتكار بالذكاء الاصطناعي' },
];

export const MOCK_STATUS = [
  { id: 1, name: 'On Duty', nameAr: 'في الخدمة', isActive: true, colorCode: '#28a745' },
  { id: 2, name: 'Vacation', nameAr: 'إجازة', isActive: true, colorCode: '#ffc107' },
  { id: 3, name: 'Sick Leave', nameAr: 'إجازة مرضية', isActive: true, colorCode: '#dc3545' },
  { id: 4, name: 'Mission', nameAr: 'مهمة', isActive: true, colorCode: '#17a2b8' },
  { id: 5, name: 'Business Trip', nameAr: 'رحلة عمل', isActive: true, colorCode: '#007bff' },
  { id: 6, name: 'Training', nameAr: 'تدريب', isActive: true, colorCode: '#6c757d' },
];

export const PRESET_COLORS = [
  '#00AB55',
  '#000000',
  '#FFFFFF',
  '#FFC0CB',
  '#FF4842',
  '#1890FF',
  '#94D82D',
  '#FFC107',
  '#04297A',
  '#7A0C2E',
];

export const _levels = Array.from({ length: 3 }, (_, index) => ({
  id: index + 1,
  value: index + 1,
}));

export const userRights = [
  {
    id: 37,
    moduleId: 1,
    moduleAccessId: 1,
    name: 'Create',
    isSelected: true,
    moduleName: 'Project',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'Create Projects',
    refinedArabicName: 'إنشاء المشاريع',
  },
  {
    id: 38,
    moduleId: 1,
    moduleAccessId: 2,
    name: 'ViewAll',
    isSelected: true,
    moduleName: 'Project',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'View All projects details',
    refinedArabicName: 'عرض تفاصيل جميع المشاريع (حتى إذا لم يكن عضوًا)',
  },
  {
    id: 39,
    moduleId: 2,
    moduleAccessId: 3,
    name: 'Create',
    isSelected: false,
    moduleName: 'Meeting',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'Create Meetings',
    refinedArabicName: 'إنشاء الاجتماعات',
  },
  {
    id: 40,
    moduleId: 3,
    moduleAccessId: 4,
    name: 'ViewAll',
    isSelected: true,
    moduleName: 'Client',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'View All clients ',
    refinedArabicName: 'عرض جميع العملاء (حتى إذا لم يكن عضوًا)',
  },
  {
    id: 41,
    moduleId: 4,
    moduleAccessId: 5,
    name: 'Create',
    isSelected: true,
    moduleName: 'Employee',
    createdOn: '0001-01-01T00:00:00.0000000+00:00',
    createdBy: null,
    updatedOn: null,
    updatedBy: null,
    refinedName: 'Mark as admin',
    refinedArabicName:
      'التعيين كمدير (يمكن للمدير عرض لوحة تحكم المدير، إضافة/حذف الموظفين، تعديل الهيكل التنظيمي، عرض تفاصيل الموظفين، إلخ.)',
  },
];

export const department_levels = [
  {
    id: 1,
    name: 'Department',
    nameAr: 'قسم',
    noOfEmployees: 5,
    isActive: true,
    departments: [
      { id: 1, name: 'IT', nameAr: 'تكنولوجيا المعلومات', noOfEmployees: 5 },
      { id: 2, name: 'HR', nameAr: 'الموارد البشرية', noOfEmployees: 5 },
      { id: 3, name: 'Development', nameAr: 'التطوير', noOfEmployees: 5 },
      { id: 4, name: 'Design', nameAr: 'التصميم', noOfEmployees: 5 },
    ],
  },
  {
    id: 2,
    name: 'Division',
    nameAr: 'إدارة',
    noOfEmployees: 8,
    isActive: true,
    divisions: [
      {
        id: 1,
        name: 'Software Development',
        nameAr: 'تطوير البرمجيات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 2,
        name: 'Network Administration ',
        nameAr: 'إدارة الشبكات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 3,
        name: 'Recruitment and Talent Acquisition',
        nameAr: 'التوظيف واكتساب المواهب',
        noOfEmployees: 5,
        deptName: 'HR',
        deptNameAr: 'الموارد البشرية',
      },
      {
        id: 4,
        name: 'Graphic Design',
        nameAr: 'تصميم الجرافيك',
        noOfEmployees: 5,
        deptName: 'Design',
        deptNameAr: 'التصميم',
      },
    ],
  },
  {
    id: 3,
    name: 'Section',
    nameAr: 'قسم فرعي',
    noOfEmployees: 20,
    isActive: true,
    sections: [
      {
        id: 1,
        name: 'Frontend Development',
        nameAr: 'تطوير الويب',
        noOfEmployees: 5,
        divName: 'Software Development',
        divNameAr: 'تطوير البرمجيات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 2,
        name: 'Network Security',
        nameAr: 'أمان الشبكات',
        noOfEmployees: 5,
        divName: 'Network Administration ',
        divNameAr: 'إدارة الشبكات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 3,
        name: 'Talent Sourcing',
        nameAr: 'البحث عن الموظفين',
        noOfEmployees: 5,
        divName: 'Recruitment and Talent Acquisition',
        divNameAr: 'التوظيف واكتساب المواهب',
        noOfEmployees: 5,
        deptName: 'HR',
        deptNameAr: 'الموارد البشرية',
      },
      {
        id: 4,
        name: 'Branding and Identity Design',
        nameAr: 'تصميم العلامة التجارية والهوية',
        divName: 'Graphic Design',
        divNameAr: 'تصميم الجرافيك',
        noOfEmployees: 5,
        deptName: 'Design',
        deptNameAr: 'التصميم',
      },
    ],
  },
  {
    id: 4,
    name: 'Session',
    nameAr: 'وحدة',
    noOfEmployees: 12,
    isActive: true,
    sessions: [
      {
        id: 1,
        name: 'Angular',
        nameAe: 'Angular',
        secName: 'Frontend Development',
        secNameAr: 'تطوير الويب',
        noOfEmployees: 5,
        divName: 'Software Development',
        divNameAr: 'تطوير البرمجيات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 2,
        name: 'Firewalls',
        nameAe: 'Firewalls',
        secName: 'Network Security',
        secNameAr: 'أمان الشبكات',
        noOfEmployees: 5,
        divName: 'Network Administration ',
        divNameAr: 'إدارة الشبكات',
        noOfEmployees: 5,
        deptName: 'IT',
        deptNameAr: 'تكنولوجيا المعلومات',
      },
      {
        id: 3,
        name: 'Evaluating Candidate',
        nameAr: 'Evaluating Candidate',
        secName: 'Talent Sourcing',
        secNameAr: 'البحث عن الموظفين',
        noOfEmployees: 5,
        divName: 'Recruitment and Talent Acquisition',
        divNameAr: 'التوظيف واكتساب المواهب',
        noOfEmployees: 5,
        deptName: 'HR',
        deptNameAr: 'الموارد البشرية',
      },
      {
        id: 4,
        name: 'Logo Design',
        nameAr: 'Logo Design',
        secName: 'Branding and Identity Design',
        secNameAr: 'تصميم العلامة التجارية والهوية',
        divName: 'Graphic Design',
        divNameAr: 'تصميم الجرافيك',
        noOfEmployees: 5,
        deptName: 'Design',
        deptNameAr: 'التصميم',
      },
    ],
  },
];

export const task_stats = [
  {
    id: 1,
    count: 12,
    name: 'Completed on time',
    color: '#2B9F57',
  },
  {
    id: 2,
    count: 5,
    name: 'Completed late',
    color: '#B5DE6E',
  },
  {
    id: 3,
    count: 1,
    name: 'Overdue',
    color: '#DF2E2E',
  },
  {
    id: 4,
    count: 7,
    name: 'Working on',
    color: '#FFB85A',
  },
  {
    id: 5,
    count: 3,
    name: 'Not started',
    color: '#236EC0',
  },
  {
    id: 6,
    count: 2,
    name: 'On hold',
    color: '#8EBFCE',
  },
  {
    id: 7,
    count: 4,
    name: 'Waiting for approval',
    color: '#23C0AB',
  },
];

export const my_task_stats = [
  {
    id: 1,
    count: 2,
    name: 'Completed on time',
    color: '#2B9F57',
  },
  {
    id: 2,
    count: 3,
    name: 'Completed late',
    color: '#B5DE6E',
  },
  {
    id: 3,
    count: 0,
    name: 'Overdue',
    color: '#DF2E2E',
  },
  {
    id: 4,
    count: 1,
    name: 'Working on',
    color: '#FFB85A',
  },
  {
    id: 5,
    count: 2,
    name: 'Not started',
    color: '#236EC0',
  },
  {
    id: 6,
    count: 0,
    name: 'On hold',
    color: '#8EBFCE',
  },
  {
    id: 7,
    count: 2,
    name: 'Waiting for approval',
    color: '#23C0AB',
  },
];

export const project_stat = [
  {
    id: 101,
    count: 12,
    name: 'Hawala',
  },
  {
    id: 102,
    count: 5,
    name: 'Islam Web',
  },
  {
    id: 103,
    count: 1,
    name: 'Zeta',
  },
  {
    id: 104,
    count: 7,
    name: 'Tairra',
  },
  {
    id: 105,
    count: 7,
    name: 'Mahami',
  },
];

export const client_stat = [
  {
    id: 1,
    count: 5,
    name: 'Total Clients',
  },
  {
    id: 2,
    count: 2,
    name: 'Total Leads',
  },
  {
    id: 3,
    count: 3,
    name: 'Active Clients',
  },
  {
    id: 4,
    amount: 5000,
    name: 'Sales Target',
  },
  {
    id: 5,
    amount: 3000,
    name: 'Leads Amount',
  },
  {
    id: 6,
    amount: 2000,
    name: 'Awarded Amount',
  },
  {
    id: 7,
    amount: 1000,
    name: 'Rejected Amount',
  },
];

export const user_gender = [
  {
    value: 1,
    label: 'Male',
  },
  {
    value: 2,
    label: 'Female',
  },
];

export const mock_projectData = {
  employeeList: [
    {
      firstName: 'Alice Johnson',
      photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-3.webp`,

      assignedTaskCounts: {
        assignedStarted: 0,
        approval: 2,
        completed: 1,
        rejected: 0,
        onHold: 0,
        assignedNotStarted: 3,
      },
    },
    {
      firstName: 'Charlie Green',
      photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-5.webp`,

      assignedTaskCounts: {
        assignedStarted: 1,
        approval: 5,
        completed: 0,
        rejected: 4,
        onHold: 0,
        assignedNotStarted: 0,
      },
    },
    {
      firstName: 'David Black',
      photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-6.webp`,
      assignedTaskCounts: {
        assignedStarted: 0,
        approval: 0,
        completed: 0,
        rejected: 0,
        onHold: 0,
        assignedNotStarted: 0,
      },
    },
    {
      firstName: 'Eve Adams',
      photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,

      assignedTaskCounts: {
        assignedStarted: 0,
        approval: 0,
        completed: 0,
        rejected: 0,
        onHold: 0,
        assignedNotStarted: 0,
      },
    },
  ],

  noneMembersEmployeeList: [
    {
      firstName: 'Bob White',
      photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-4.webp`,
      assignedTaskCounts: {
        assignedStarted: 0,
        approval: 2,
        completed: 1,
        rejected: 0,
        onHold: 0,
        assignedNotStarted: 3,
      },
    },
  ],
};

export const projectTaskTypes = [
  { id: 1, name: 'Planning', nameAr: 'تخطيط' },
  { id: 2, name: 'Development', nameAr: 'تطوير' },
  { id: 3, name: 'Testing', nameAr: 'اختبار' },
  { id: 4, name: 'Deployment', nameAr: 'نشر' },
  { id: 5, name: 'Documentation', nameAr: 'توثيق' },
];

export const projectModules = [
  { id: 1, name: 'Overview', nameAr: 'نظرة عامة' },
  { id: 2, name: 'Tasks', nameAr: 'المهام' },
  { id: 3, name: 'Milestones', nameAr: 'المعالم' },
  { id: 4, name: 'Timeline', nameAr: 'الجدول الزمني' },
  { id: 5, name: 'Resources', nameAr: 'الموارد' },
  { id: 6, name: 'Documents', nameAr: 'الوثائق' },
  { id: 7, name: 'Budget', nameAr: 'الميزانية' },
  { id: 8, name: 'Risks', nameAr: 'المخاطر' },
  { id: 9, name: 'Communication', nameAr: 'الاتصالات' },
  { id: 10, name: 'Reports', nameAr: 'التقارير' },
];

export const projectMilestones = [
  { id: 1, name: 'Project Initiation', nameAr: 'بدء المشروع' },
  { id: 2, name: 'Requirement Finalization', nameAr: 'الانتهاء من المتطلبات' },
  { id: 3, name: 'Design Approval', nameAr: 'الموافقة على التصميم' },
  { id: 4, name: 'Development Complete', nameAr: 'انتهاء التطوير' },
  { id: 5, name: 'Testing Complete', nameAr: 'انتهاء الاختبار' },
  { id: 6, name: 'UAT Sign-off', nameAr: 'توقيع المستخدم النهائي' },
  { id: 7, name: 'Go-Live', nameAr: 'تشغيل المشروع' },
  { id: 8, name: 'Project Closure', nameAr: 'إغلاق المشروع' },
];

export const projectMissions = [
  { id: 1, name: 'Define Project Scope', nameAr: 'تحديد نطاق المشروع' },
  { id: 2, name: 'Align Stakeholders', nameAr: 'مواءمة أصحاب المصلحة' },
  { id: 3, name: 'Ensure Resource Allocation', nameAr: 'ضمان تخصيص الموارد' },
  { id: 4, name: 'Maintain Timeline Adherence', nameAr: 'الالتزام بالجدول الزمني' },
  { id: 5, name: 'Ensure Quality Standards', nameAr: 'ضمان معايير الجودة' },
  { id: 6, name: 'Risk Management', nameAr: 'إدارة المخاطر' },
  { id: 7, name: 'Achieve Client Satisfaction', nameAr: 'تحقيق رضا العميل' },
  { id: 8, name: 'Deliver Value', nameAr: 'تقديم القيمة' },
];
