import { CONFIG } from 'src/config-global';
import { useTranslation } from 'react-i18next';

export const mock_clients = [
  {
    clientId: '101',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'CEO',
    department: 'Management',
    email: 'nannie.abernathy70@yahoo.com',
    address: '908 Jack Locks',
    name: 'Tech Innovators Inc.',
    userName: 'Jayvion101',
    isVerified: true,
    company: 'Lueilwitz and Sons',
    country: 'United States',
    avatarUrl: '/assets/images/mock/avatar/avatar-1.webp',
    phoneNumber: '+1 202-555-0143',
    type: 'leads',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Abu Dhabi',
    location: 'Mushrif Park',
    website: 'www.google.com',
    members: [
      {
        id: 1,
        firstName: 'John Doe',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-1.webp`,
        email: 'johnDoe@gmail.com',
      },
      {
        id: 2,
        firstName: 'Jane Smith',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-2.webp`,
        email: 'janeSmith@gmail.com',
      },
    ],
    leadCount: 1,
    leadAmount: 10000,
    salesAmount: 10000,
    rejectedAmount: 0,
  },
  {
    clientId: '102',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'CTO',
    department: 'Management',
    email: 'ashlynn.ohara62@gmail.com',
    address: '908 Jack Locks',
    name: 'Global Solutions Ltd.',
    userName: 'Lucian102',
    isVerified: true,
    company: 'Gleichner, Mueller and Tromp',
    country: 'Canada',
    avatarUrl: '/assets/images/mock/avatar/avatar-2.webp',
    phoneNumber: '+1 416-555-0198',
    type: 'members',
    empStatus: 'Vacation',
    status: 'Disabled',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
    website: 'www.abc.com',
    members: [
      {
        id: 3,
        firstName: 'Alice Johnson',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-3.webp`,
        email: 'alicJohnson@gmail.com',
      },
    ],
    leadCount: 2,
    leadAmount: 20000,
    salesAmount: 15000,
    rejectedAmount: 5000,
  },
  {
    clientId: '103',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Project Coordinator',
    department: 'IT',
    email: 'milo.farrell@hotmail.com',
    address: '908 Jack Locks',
    name: 'Apex Dynamics Corp.',
    userName: 'Deja103',
    isVerified: true,
    company: 'Nikolaus - Leuschke',
    country: 'United Kingdom',
    avatarUrl: '/assets/images/mock/avatar/avatar-3.webp',
    phoneNumber: '+44 20 7946 0958',
    type: 'clients',
    empStatus: 'Sick Leave',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
    website: 'www.pqr.com',
    members: [
      {
        id: 4,
        firstName: 'Charlie Green',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-5.webp`,
        email: 'charlieGreen@gmail.com',
      },
      {
        id: 5,
        firstName: 'David Black',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-6.webp`,
        email: 'davidBlack@gmail.com',
      },
      {
        id: 6,
        firstName: 'Eve Adams',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
        email: 'eveAdams.com',
      },
      {
        id: 7,
        firstName: 'Bob White',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-4.webp`,
        email: 'bodWhite@gmail.com',
      },
    ],
    leadCount: 1,
    leadAmount: 3000,
    salesAmount: 1000,
    rejectedAmount: 2000,
    followups: 1,
  },
  {
    clientId: '104',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Team Leader',
    department: 'IT',
    email: 'violet.ratke86@yahoo.com',
    address: '908 Jack Locks',
    name: 'Quantum Leap Industries',
    userName: 'Harrison104',
    isVerified: false,
    company: 'Hegmann, Kreiger and Bayer',
    country: 'Australia',
    avatarUrl: '/assets/images/mock/avatar/avatar-4.webp',
    phoneNumber: '+61 2 9876 5432',
    type: 'members',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
    website: 'www.123.com',
    members: [
      {
        id: 6,
        firstName: 'Eve Adams',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
        email: 'eveAdams@gmail.com',
      },
    ],
    leadCount: 4,
    leadAmount: 4000,
    salesAmount: 2000,
    rejectedAmount: 2000,
  },
  {
    clientId: '105',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Software Developer',
    department: 'IT',
    email: 'letha.lubowitz24@yahoo.com',
    address: '908 Jack Locks',
    name: 'Stellar Tech Solutions',
    userName: 'Reece105',
    isVerified: false,
    company: 'Grimes Inc',
    country: 'India',
    avatarUrl: '/assets/images/mock/avatar/avatar-5.webp',
    phoneNumber: '+91 22 1234 5678',
    type: 'clients',
    empStatus: 'Vacation',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
    website: 'www.qwerty.com',
    members: [
      {
        id: 4,
        firstName: 'Charlie Green',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-5.webp`,
        email: 'charlieGreen@gmail.com',
      },
      {
        id: 5,
        firstName: 'David Black',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-6.webp`,
        email: 'davidBlack@gmail.com',
      },
      {
        id: 6,
        firstName: 'Eve Adams',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
        email: 'eveAdams.com',
      },
      {
        id: 7,
        firstName: 'Bob White',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-4.webp`,
        email: 'bodWhite@gmail.com',
      },
    ],
    leadCount: 2,
    leadAmount: 3000,
    salesAmount: 2000,
    rejectedAmount: 1000,
  },
  {
    clientId: '106',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Marketing Strategist',
    department: 'Marketing',
    email: 'aditya.greenfelder31@gmail.com',
    address: '908 Jack Locks',
    name: 'Dynamic Marketing Group',
    userName: 'Lainey106',
    isVerified: true,
    company: 'Durgan - Murazik',
    country: 'Germany',
    avatarUrl: '/assets/images/mock/avatar/avatar-6.webp',
    phoneNumber: '+49 30 123456',
    type: 'members',
    empStatus: 'Sick Leave',
    status: 'Active',
    password: '',
    emirates: 'Abu Dhabi',
    location: 'Mushrif Park',
    website: 'www.client.com',
  },
  {
    clientId: '107',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Data Analyst',
    department: 'IT',
    email: 'lenna.bergnaum27@hotmail.com',
    address: '908 Jack Locks',
    name: 'Data Insights Co.',
    userName: 'Cristopher107',
    isVerified: false,
    company: 'Altenwerth, Medhurst and Roberts',
    country: 'France',
    avatarUrl: '/assets/images/mock/avatar/avatar-7.webp',
    phoneNumber: '+33 1 23456789',
    type: 'leads',
    empStatus: 'Vacation',
    status: 'Disabled',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '108',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Product Owner',
    department: 'Management',
    email: 'luella.ryan33@gmail.com',
    address: '908 Jack Locks',
    name: 'Innovate Products Group',
    userName: 'Melanie108',
    isVerified: false,
    company: 'Raynor Group',
    country: 'Japan',
    avatarUrl: '/assets/images/mock/avatar/avatar-8.webp',
    phoneNumber: '+81 3 1234 5678',
    type: 'members',
    empStatus: 'On Duty',
    status: 'Disabled',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '109',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b9',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Graphic Designer',
    department: 'IT',
    email: 'joana.simonis84@gmail.com',
    address: '908 Jack Locks',
    name: 'Creative Visuals Agency',
    userName: 'Chase109',
    isVerified: false,
    company: 'Mraz, Donnelly and Collins',
    country: 'China',
    avatarUrl: '/assets/images/mock/avatar/avatar-9.webp',
    phoneNumber: '+86 10 1234 5678',
    type: 'clients',
    empStatus: 'Vacation',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '110',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b10',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Operations Manager',
    department: 'IT',
    email: 'marjolaine.white94@gmail.com',
    address: '908 Jack Locks',
    name: 'Streamline Operations Inc.',
    userName: 'Shawn110',
    isVerified: false,
    company: 'Padberg - Bailey',
    country: 'Brazil',
    avatarUrl: '/assets/images/mock/avatar/avatar-10.webp',
    phoneNumber: '+55 11 2345-6789',
    type: 'members',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '111',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b11',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Customer Support Specialist',
    department: 'Management',
    email: 'vergie.block82@hotmail.com',
    address: '908 Jack Locks',
    name: 'Customer First Solutions',
    userName: 'Soren111',
    isVerified: true,
    company: 'Heidenreich, Stokes and Parker',
    country: 'South Africa',
    avatarUrl: '/assets/images/mock/avatar/avatar-11.webp',
    phoneNumber: '+27 11 123 4567',
    type: 'clients',
    empStatus: 'On Duty',
    status: 'Disabled',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '112',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b12',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Sales Manager',
    department: 'Management',
    email: 'vito.hudson@hotmail.com',
    address: '908 Jack Locks',
    name: 'Sales Drive Enterprises',
    userName: 'Cortez112',
    isVerified: true,
    company: 'Pagac and Sons',
    country: 'Russia',
    avatarUrl: '/assets/images/mock/avatar/avatar-12.webp',
    phoneNumber: '+7 495 123-4567',
    type: 'members',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Abu Dhabi',
    location: 'Mushrif Park',
  },
  {
    clientId: '113',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b13',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'HR Recruiter',
    department: 'Human Resources',
    email: 'tyrel.greenholt@gmail.com',
    address: '908 Jack Locks',
    name: 'People First Recruiters',
    userName: 'Brycen113',
    isVerified: true,
    company: 'Rempel, Hand and Herzog',
    country: 'Mexico',
    avatarUrl: '/assets/images/mock/avatar/avatar-13.webp',
    phoneNumber: '+52 55 1234 5678',
    type: 'leads',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '114',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b14',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Business Consultant',
    department: 'IT',
    email: 'dwight.block85@yahoo.com',
    address: '908 Jack Locks',
    name: 'Strategic Growth Advisors',
    userName: 'Giana114',
    isVerified: false,
    company: 'Dare - Treutel',
    country: 'Italy',
    avatarUrl: '/assets/images/mock/avatar/avatar-14.webp',
    phoneNumber: '+39 06 123 4567',
    type: 'members',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '115',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b15',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Financial Planner',
    department: 'Finance',
    email: 'mireya13@hotmail.com',
    address: '908 Jack Locks',
    name: 'Wealth Builders Group',
    userName: 'Aspen115',
    isVerified: false,
    company: 'Kihn, Marquardt and Crist',
    country: 'Spain',
    avatarUrl: '/assets/images/mock/avatar/avatar-15.webp',
    phoneNumber: '+34 91 123 4567',
    type: 'clients',
    empStatus: 'Sick Leave',
    status: 'Disabled',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '116',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b16',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Network Engineer',
    department: 'IT',
    email: 'dasia.jenkins@hotmail.com',
    address: '908 Jack Locks',
    name: 'Secure Networks Corp.',
    userName: 'Colten116',
    isVerified: false,
    company: 'Nolan - Kunde',
    country: 'Netherlands',
    avatarUrl: '/assets/images/mock/avatar/avatar-16.webp',
    phoneNumber: '+31 20 123 4567',
    type: 'members',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '117',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b17',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Content Creator',
    department: 'IT',
    email: 'benny89@yahoo.com',
    address: '908 Jack Locks',
    name: 'Content Kings Media',
    userName: 'Angelique117',
    isVerified: true,
    company: 'Wuckert Inc',
    country: 'Sweden',
    avatarUrl: '/assets/images/mock/avatar/avatar-17.webp',
    phoneNumber: '+46 8 123 456',
    type: 'clients',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Abu Dhabi',
    location: 'Mushrif Park',
  },
  {
    clientId: '118',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b18',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Quality Assurance Tester',
    department: 'Quality Assurance',
    email: 'dawn.goyette@gmail.com',
    address: '908 Jack Locks',
    name: 'Precision QA Solutions',
    userName: 'Selina118',
    isVerified: false,
    company: 'Dibbert Inc',
    country: 'Switzerland',
    avatarUrl: '/assets/images/mock/avatar/avatar-18.webp',
    phoneNumber: '+41 22 123 45 67',
    type: 'members',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '119',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b19',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'Public Relations Officer',
    department: 'Management',
    email: 'zella.hickle4@yahoo.com',
    address: '908 Jack Locks',
    name: 'Public Image Strategies',
    userName: 'Lawson119',
    isVerified: false,
    company: 'Goyette and Sons',
    country: 'South Korea',
    avatarUrl: '/assets/images/mock/avatar/avatar-19.webp',
    phoneNumber: '+82 2 123 4567',
    type: 'leads',
    empStatus: 'On Duty',
    status: 'Active',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
  {
    clientId: '120',
    id: 'e99f09a7-dd88-49d5-b1c8-1daf80c2d7b20',
    zipCode: '85807',
    state: 'Virginia',
    city: 'Rancho Cordova',
    role: 'IT Administrator',
    department: 'IT',
    email: 'avery43@hotmail.com',
    address: '908 Jack Locks',
    name: 'System Support Solutions',
    userName: 'Ariana120',
    isVerified: false,
    company: 'Feest Group',
    country: 'Argentina',
    avatarUrl: '/assets/images/mock/avatar/avatar-20.webp',
    phoneNumber: '+54 11 1234-5678',
    type: 'members',
    empStatus: 'Vacation',
    status: 'Disabled',
    password: '',
    emirates: 'Dubai',
    location: 'Jumeira',
  },
];

export const clients = [`All Clients`, `My Clients`];

export const vendors = [`All Vendors`, `My Vendors`];

export const status = [`Active`, `Disabled`];

export const STATUS_OPTIONS = [
  { value: 'members', label: 'Open' },
  { value: 'clients', label: 'Awarded' },
  { value: 'leads', label: 'Rejected' },
];

export const emirates = [
  'Dubai',
  'Abu Dhabi',
  'Sharjah',
  'Ajman',
  'Umm Al-Quwain',
  'Fujairah',
  'Ras Al Khaimah',
  'Al Ain',
];

export const locations = [
  'Jumeira (Dubai)',
  'Downtown Dubai (Dubai)',
  'Dubai Marina (Dubai)',
  'Al Barsha (Dubai)',
  'Al Safa (Dubai)',
  'Business Bay (Dubai)',
  'Deira (Dubai)',
  'Al Nahda (Sharjah)',
  'Al Wahda (Abu Dhabi)',
  'Corniche (Abu Dhabi)',
  'Mushrif Park (Abu Dhabi)',
  'Al Ain (Abu Dhabi)',
  'Rolla (Sharjah)',
  'Al Majaz (Sharjah)',
  'Al Qasba (Sharjah)',
  'Saadiyat Island (Abu Dhabi)',
  'Al Reem Island (Abu Dhabi)',
  'Khalid Lagoon (Sharjah)',
  'Al Dhait (Ras Al Khaimah)',
  'Rolla Square (Sharjah)',
];

export const mock_leads = [
  {
    id: 1,
    leadId: 101,
    name: 'John Doe',
    leadAmount: 15000,
    status: 'Under approval',
    source: 'Google Ads',
    percentageOfSuccess: 20,
    type: 'leads',
    currency: 'AED',
  },
  {
    id: 2,
    leadId: 102,
    name: 'Jane Smith',
    leadAmount: 25000,
    status: 'Open',
    source: 'Referral',
    percentageOfSuccess: 70,
    type: 'awarded',
    awardedAmount: '1000',
    currency: 'AED',
  },
  {
    id: 3,
    leadId: 103,
    name: 'Alice Johnson',
    leadAmount: 35000,
    status: 'In Progress',
    source: 'Website',
    percentageOfSuccess: 40,
    type: 'leads',
    currency: 'SAR',
  },
  {
    id: 4,
    leadId: 104,
    name: 'Bob Brown',
    leadAmount: 18000,
    status: 'Closed',
    source: 'Email Campaign',
    percentageOfSuccess: 80,
    type: 'rejected',
    rejectedReason: 'No answer from client',
    currency: 'QAR',
  },
  {
    id: 5,
    leadId: 105,
    name: 'Charlie White',
    leadAmount: 5000,
    status: 'Open',
    source: 'Social Media',
    percentageOfSuccess: 50,
    type: 'leads',
  },
  {
    id: 6,
    leadId: 106,
    name: 'Emily Clark',
    leadAmount: 22000,
    status: 'Closed',
    source: 'Referral',
    percentageOfSuccess: 85,
    type: 'awarded',
    awardedAmount: '2000',
    currency: 'QAR',
  },
  {
    id: 7,
    leadId: 107,
    name: 'David Lee',
    leadAmount: 40000,
    status: 'In Progress',
    source: 'Google Ads',
    percentageOfSuccess: 65,
    type: 'awarded',
    awardedAmount: '3000',
    currency: 'AED',
  },
  {
    id: 8,
    leadId: 108,
    name: 'Olivia Martin',
    leadAmount: 17000,
    status: 'Open',
    source: 'Website',
    percentageOfSuccess: 75,
    type: 'rejected',
    rejectedReason: 'No longer interested',
    currency: 'AED',
  },
  {
    id: 9,
    leadId: 109,
    name: 'Ethan Harris',
    leadAmount: 32000,
    status: 'Closed',
    source: 'Email Campaign',
    percentageOfSuccess: 90,
    type: 'rejected',
    rejectedReason: 'Client did not like the pricing model',
    currency: 'AED',
  },
  {
    id: 10,
    leadId: 110,
    name: 'Sophia Wilson',
    leadAmount: 15000,
    status: 'In Progress',
    source: 'Social Media',
    percentageOfSuccess: 70,
    type: 'leads',
    currency: 'AED',
  },
  {
    id: 11,
    leadId: 111,
    name: 'Lucas Walker',
    leadAmount: 28000,
    status: 'Closed',
    source: 'Referral',
    percentageOfSuccess: 80,
    type: 'leads',
    currency: 'AED',
  },
  {
    id: 12,
    leadId: 112,
    name: 'Mia Thompson',
    leadAmount: 22000,
    status: 'Open',
    source: 'Google Ads',
    percentageOfSuccess: 60,
    type: 'awarded',
    awardedAmount: '4000',
    currency: 'AED',
  },
  {
    id: 13,
    leadId: 113,
    name: 'James Lewis',
    leadAmount: 30000,
    status: 'In Progress',
    source: 'Website',
    percentageOfSuccess: 75,
    type: 'awarded',
    awardedAmount: '5000',
    currency: 'AED',
  },
  {
    id: 14,
    leadId: 114,
    name: 'Chloe Scott',
    leadAmount: 14000,
    status: 'Closed',
    source: 'Email Campaign',
    percentageOfSuccess: 65,
    type: 'leads',
    currency: 'AED',
  },
  {
    id: 15,
    leadId: 115,
    name: 'William Robinson',
    leadAmount: 25000,
    status: 'Open',
    source: 'Referral',
    percentageOfSuccess: 80,
    type: 'rejected',
    rejectedReason: 'Client did not like the pricing model',
    currency: 'AED',
  },
  {
    id: 16,
    leadId: 116,
    name: 'Grace Walker',
    leadAmount: 19000,
    status: 'In Progress',
    source: 'Social Media',
    percentageOfSuccess: 55,
    type: 'rejected',
    rejectedReason: 'No answer from client',
    currency: 'AED',
  },
];

export const leads = [`All Leads`, `My Leads`];

export const _members = [
  {
    id: 1,
    firstName: 'John Doe',
    photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-1.webp`,
    email: 'johnDoe@gmail.com',
  },
  {
    id: 2,
    firstName: 'Jane Smith',
    photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-2.webp`,
    email: 'janeSmith@gmail.com',
  },
  {
    id: 3,
    firstName: 'Alice Johnson',
    photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-3.webp`,
    email: 'AliceJohnson@gmail.com',
  },
  {
    id: 4,
    firstName: 'Charlie Green',
    photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-5.webp`,
    email: 'charlieGreen@gmail.com',
  },
  {
    id: 5,
    firstName: 'David Black',
    photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-6.webp`,
    email: 'davidBlack@gmail.com',
  },
  {
    id: 6,
    firstName: 'Eve Adams',
    photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
    email: 'eveAdams@gmail.com',
  },
  {
    id: 7,
    firstName: 'Bob White',
    photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-4.webp`,
    email: 'bobWhite@gmail.com',
  },
  // {
  //   id: 8,
  //   firstName: 'Jaydon Frankie',
  //   photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-25.webp`,
  //   email: 'demo@minimals.cc',
  // },
];

export const mock_members = [
  {
    groupId: '101',
    id: '1',
    name: 'The Closer Crew',
    members: [
      {
        id: 1,
        firstName: 'John Doe',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-1.webp`,
        email: 'johnDoe@gmail.com',
      },
      {
        id: 2,
        firstName: 'Jane Smith',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-2.webp`,
        email: 'janeSmith@gmail.com',
      },
    ],
    leadCount: 1,
    leadAmount: 10000,
    salesAmount: 10000,
    rejectedAmount: 0,
  },
  {
    groupId: '102',
    id: '2',
    name: 'Revenue Runners',
    members: [
      {
        id: 3,
        firstName: 'Alice Johnson',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-3.webp`,
        email: 'alicJohnson@gmail.com',
      },
    ],
    leadCount: 2,
    leadAmount: 20000,
    salesAmount: 15000,
    rejectedAmount: 5000,
  },
  {
    groupId: '103',
    id: '3',
    name: 'Profit Pioneers',
    members: [
      {
        id: 4,
        firstName: 'Charlie Green',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-5.webp`,
        email: 'charlieGreen@gmail.com',
      },
      {
        id: 5,
        firstName: 'David Black',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-6.webp`,
        email: 'davidBlack@gmail.com',
      },
      {
        id: 6,
        firstName: 'Eve Adams',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
        email: 'eveAdams.com',
      },
      {
        id: 7,
        firstName: 'Bob White',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-4.webp`,
        email: 'bodWhite@gmail.com',
      },
    ],
    leadCount: 1,
    leadAmount: 3000,
    salesAmount: 1000,
    rejectedAmount: 2000,
    followups: 1,
  },
  {
    groupId: '104',
    id: '4',
    name: 'Revenue Makers',
    members: [
      {
        id: 6,
        firstName: 'Eve Adams',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
        email: 'eveAdams@gmail.com',
      },
    ],
    leadCount: 4,
    leadAmount: 4000,
    salesAmount: 2000,
    rejectedAmount: 2000,
  },
  {
    groupId: '105',
    id: '5',
    name: 'Lead Hunters',
    members: [
      {
        id: 4,
        firstName: 'Charlie Green',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-5.webp`,
        email: 'charlieGreen@gmail.com',
      },
      {
        id: 5,
        firstName: 'David Black',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-6.webp`,
        email: 'davidBlack@gmail.com',
      },
      {
        id: 6,
        firstName: 'Eve Adams',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-7.webp`,
        email: 'eveAdams.com',
      },
      {
        id: 7,
        firstName: 'Bob White',
        photoPath: `${CONFIG.assetsDir}/assets/images/mock/avatar/avatar-4.webp`,
        email: 'bodWhite@gmail.com',
      },
    ],
    leadCount: 2,
    leadAmount: 3000,
    salesAmount: 2000,
    rejectedAmount: 1000,
  },
  {
    groupId: '106',
    id: '6',
    name: 'Sales Surge',
  },
  {
    groupId: '107',
    id: '7',
    name: 'Profit Pros',
  },
  {
    groupId: '108',
    id: '8',
    name: 'Closing Titans',
  },
  {
    groupId: '109',
    id: '9',
    name: 'Pipeline Powerhouses',
  },
  {
    groupId: '110',
    id: '10',
    name: 'The Deal Makers',
  },
];

export const years = ['2024', '2025', '2026'];
export const months = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
export const sales_report = [
  {
    id: 1,
    totalAchieved: '100000',
    target: '9800000',
    remaining: '9700000',
    year: '2025',
    monthlyValue: [
      {
        id: 1,
        month: 'Jan',
        totalAchieved: '60000',
        target: '500000',
        remaining: '0',
      },
      {
        id: 2,
        month: 'Feb',
        totalAchieved: '40000',
        target: '500000',
        remaining: '0',
      },
      {
        id: 3,
        month: 'Mar',
        totalAchieved: '20000',
        target: '500000',
        remaining: '0',
      },
      {
        id: 4,
        month: 'Apr',
        totalAchieved: '80000',
        target: '500000',
        remaining: '0',
      },
      {
        id: 5,
        month: 'May',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
      {
        id: 6,
        month: 'Jun',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
      {
        id: 7,
        month: 'Jul',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
      {
        id: 8,
        month: 'Aug',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
      {
        id: 9,
        month: 'Sep',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
      {
        id: 10,
        month: 'Oct',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
      {
        id: 11,
        month: 'Nov',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
      {
        id: 12,
        month: 'Dec',
        totalAchieved: '0',
        target: '500000',
        remaining: '0',
      },
    ],
  },
  {
    id: 2,
    totalAchieved: '8800000',
    target: '9800000',
    remaining: '100000',
    year: '2024',
    monthlyValue: [
      {
        id: 1,
        month: 'Jan',
        totalAchieved: '300000',
        target: '500000',
        remaining: '200000',
      },
      {
        id: 2,
        month: 'Feb',
        totalAchieved: '320000',
        target: '500000',
        remaining: '180000',
      },
      {
        id: 3,
        month: 'Mar',
        totalAchieved: '350000',
        target: '500000',
        remaining: '150000',
      },
      {
        id: 4,
        month: 'Apr',
        totalAchieved: '100000',
        target: '500000',
        remaining: '220000',
      },
      {
        id: 5,
        month: 'May',
        totalAchieved: '230000',
        target: '500000',
        remaining: '140000',
      },
      {
        id: 6,
        month: 'Jun',
        totalAchieved: '330000',
        target: '500000',
        remaining: '170000',
      },
      {
        id: 7,
        month: 'Jul',
        totalAchieved: '370000',
        target: '500000',
        remaining: '130000',
      },
      {
        id: 8,
        month: 'Aug',
        totalAchieved: '380000',
        target: '500000',
        remaining: '120000',
      },
      {
        id: 9,
        month: 'Sep',
        totalAchieved: '340000',
        target: '500000',
        remaining: '160000',
      },
      {
        id: 10,
        month: 'Oct',
        totalAchieved: '310000',
        target: '500000',
        remaining: '190000',
      },
      {
        id: 11,
        month: 'Nov',
        totalAchieved: '360000',
        target: '500000',
        remaining: '140000',
      },
      {
        id: 12,
        month: 'Dec',
        totalAchieved: '400000',
        target: '500000',
        remaining: '100000',
      },
    ],
  },
  {
    id: 3,
    totalAchieved: '3800000',
    target: '8800000',
    remaining: '100000',
    year: '2023',
    monthlyValue: [
      {
        id: 1,
        month: 'Jan',
        totalAchieved: '100000',
        target: '500000',
        remaining: '200000',
      },
      {
        id: 2,
        month: 'Feb',
        totalAchieved: '120000',
        target: '500000',
        remaining: '180000',
      },
      {
        id: 3,
        month: 'Mar',
        totalAchieved: '250000',
        target: '0',
        remaining: '150000',
      },
      {
        id: 4,
        month: 'Apr',
        totalAchieved: '220000',
        target: '500000',
        remaining: '220000',
      },
      {
        id: 5,
        month: 'May',
        totalAchieved: '360000',
        target: '500000',
        remaining: '140000',
      },
      {
        id: 6,
        month: 'Jun',
        totalAchieved: '330000',
        target: '500000',
        remaining: '170000',
      },
      {
        id: 7,
        month: 'Jul',
        totalAchieved: '370000',
        target: '500000',
        remaining: '130000',
      },
      {
        id: 8,
        month: 'Aug',
        totalAchieved: '380000',
        target: '500000',
        remaining: '120000',
      },
      {
        id: 9,
        month: 'Sep',
        totalAchieved: '340000',
        target: '500000',
        remaining: '160000',
      },
      {
        id: 10,
        month: 'Oct',
        totalAchieved: '310000',
        target: '500000',
        remaining: '190000',
      },
      {
        id: 11,
        month: 'Nov',
        totalAchieved: '360000',
        target: '500000',
        remaining: '140000',
      },
      {
        id: 12,
        month: 'Dec',
        totalAchieved: '400000',
        target: '500000',
        remaining: '100000',
      },
    ],
  },
];

export const LEAD_OPTIONS = [
  { value: 'leads', label: 'Leads' },
  { value: 'awarded', label: 'Awarded' },
  { value: 'rejected', label: 'Rejected' },
];

export const reasonList = [
  {
    id: 1,
    name: 'No answer from client',
    nameAr: 'لا إجابة من العميل',
  },
  {
    id: 2,
    name: 'No longer interested',
    nameAr: 'لم يعد مهتمًا',
  },
  {
    id: 3,
    name: 'Client did not like the pricing model',
    nameAr: 'لم يعجب العميل نموذج التسعير',
  },
];

export const salesStatus = [
  { id: 1, name: 'Pending', nameAr: 'قيد الانتظار' },
  { id: 2, name: 'Completed', nameAr: 'مكتمل' },
  { id: 3, name: 'Cancelled', nameAr: 'ملغى' },
  { id: 4, name: 'In Progress', nameAr: 'قيد التنفيذ' },
  { id: 5, name: 'On Hold', nameAr: 'معلق' },
  { id: 6, name: 'Failed', nameAr: 'فشل' },
  { id: 7, name: 'Successful', nameAr: 'ناجح' },
  { id: 8, name: 'Returned', nameAr: 'مرتجع' },
  { id: 9, name: 'Refunded', nameAr: 'مسترد' },
  { id: 10, name: 'Awaiting Payment', nameAr: 'في انتظار الدفع' },
];

export const mock_source = [
  { id: 1, name: 'Website', nameAr: 'موقع إلكتروني' },
  { id: 2, name: 'LinkedIn', nameAr: 'لينكدإن' },
  { id: 3, name: 'Twitter', nameAr: 'تويتر' },
  { id: 4, name: 'Facebook', nameAr: 'فيسبوك' },
  { id: 5, name: 'Instagram', nameAr: 'إنستغرام' },
  { id: 6, name: 'YouTube', nameAr: 'يوتيوب' },
  { id: 7, name: 'Email', nameAr: 'بريد إلكتروني' },
  { id: 8, name: 'Phone', nameAr: 'هاتف' },
];
export const CURRENCIES = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: 'AE' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', flag: 'SA' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', flag: 'QA' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: 'KW' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', flag: 'OM' },
  { code: 'USD', name: 'US Dollar', symbol: '$', flag: 'US' },
  // { code: 'EUR', name: 'Euro', symbol: '€', flag: 'EU' },
  // { code: 'GBP', name: 'British Pound', symbol: '£', flag: 'GB' },
  // { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: 'JP' },
  // { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: 'CN' },
  // { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: 'IN' },
  // { code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: 'TR' },
  // { code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: 'RU' },
  // { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', flag: 'BR' },
  // { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', flag: 'TN' },
  // { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', flag: 'AU' },
  // { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', flag: 'CA' },
  // { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', flag: 'CH' },
  // { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', flag: 'SG' },
  // { code: 'MXN', name: 'Mexican Peso', symbol: '$', flag: 'MX' },
  // { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: 'ZA' },
  // { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: 'SE' },
  // { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: 'NO' },
  // { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', flag: 'NZ' },
];

export const clientTaskTypes = [
  { id: 1, name: 'Meeting', nameAr: 'اجتماع' },
  { id: 2, name: 'Requirement Gathering', nameAr: 'جمع المتطلبات' },
  { id: 3, name: 'Feedback Review', nameAr: 'مراجعة الملاحظات' },
  { id: 4, name: 'Support', nameAr: 'دعم' },
  { id: 5, name: 'Report Sharing', nameAr: 'مشاركة التقارير' },
];

export const vendorTaskTypes = [
  { id: 1, name: 'Procurement', nameAr: 'شراء' },
  { id: 2, name: 'Follow-up', nameAr: 'متابعة' },
  { id: 3, name: 'Contract Review', nameAr: 'مراجعة العقد' },
  { id: 4, name: 'Delivery Coordination', nameAr: 'تنسيق التسليم' },
  { id: 5, name: 'Invoice Processing', nameAr: 'معالجة الفاتورة' },
];

export const mock_vendors = [
  { id: 1, name: 'IT Services', nameAr: 'خدمات تكنولوجيا المعلومات' },
  { id: 2, name: 'Construction', nameAr: 'الإنشاءات' },
  { id: 3, name: 'Logistics', nameAr: 'الخدمات اللوجستية' },
  { id: 4, name: 'Consulting', nameAr: 'الاستشارات' },
  { id: 5, name: 'Marketing Agency', nameAr: 'وكالة تسويق' },
  { id: 6, name: 'Equipment Supplier', nameAr: 'مورد المعدات' },
];

export const businessLeads = [
  { id: 0, name: 'General', nameAr: 'عام' },
  { id: 1, name: 'Potential Client', nameAr: 'عميل محتمل' },
  { id: 2, name: 'Referral', nameAr: 'إحالة' },
  { id: 3, name: 'Inbound Inquiry', nameAr: 'استفسار وارد' },
  { id: 4, name: 'Marketing Campaign', nameAr: 'حملة تسويقية' },
  { id: 5, name: 'Cold Call', nameAr: 'مكالمة باردة' },
  { id: 6, name: 'Event/Exhibition', nameAr: 'حدث/معرض' },
];
export const contracts = [
  { id: 0, name: 'General', nameAr: 'عام' },
  { id: 1, name: 'Service Agreement', nameAr: 'اتفاقية خدمة' },
  { id: 2, name: 'Non-Disclosure Agreement (NDA)', nameAr: 'اتفاقية عدم الإفشاء' },
  { id: 3, name: 'Partnership Agreement', nameAr: 'اتفاقية شراكة' },
  { id: 4, name: 'Purchase Agreement', nameAr: 'اتفاقية شراء' },
  { id: 5, name: 'Consulting Agreement', nameAr: 'اتفاقية استشارية' },
  { id: 6, name: 'Maintenance Contract', nameAr: 'عقد صيانة' },
];
